// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nqueens,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.149000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=631,HLS_SYN_LUT=1176,HLS_VERSION=2019_2}" *)

module nqueens (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [3:0] x_fu_277_p2;
wire    ap_CS_fsm_state2;
reg   [2:0] a_addr_1_reg_504;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln17_fu_316_p2;
reg   [0:0] icmp_ln17_reg_509;
wire    ap_CS_fsm_state5;
wire   [31:0] zext_ln19_fu_322_p1;
reg   [31:0] zext_ln19_reg_513;
wire    ap_CS_fsm_state6;
wire   [30:0] j_fu_332_p2;
reg   [30:0] j_reg_521;
wire   [0:0] icmp_ln19_fu_326_p2;
wire   [31:0] u_1_fu_349_p2;
wire   [0:0] icmp_ln24_fu_343_p2;
wire   [31:0] select_ln20_1_fu_412_p3;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln31_fu_420_p2;
reg   [0:0] icmp_ln31_reg_544;
wire    ap_CS_fsm_state9;
wire  signed [31:0] k_fu_426_p2;
wire   [0:0] icmp_ln33_fu_432_p2;
reg   [0:0] icmp_ln33_reg_553;
wire   [31:0] k_5_fu_457_p2;
wire    ap_CS_fsm_state10;
wire   [31:0] iteration_fu_480_p2;
wire   [0:0] icmp_ln42_fu_463_p2;
reg   [2:0] a_address0;
reg    a_ce0;
reg    a_we0;
reg   [31:0] a_d0;
wire   [31:0] a_q0;
reg   [3:0] x_0_reg_90;
wire   [0:0] icmp_ln10_fu_271_p2;
reg   [0:0] ap_phi_mux_flag_1_phi_fu_233_p4;
reg   [0:0] flag_0_reg_101;
reg   [31:0] iteration_0_reg_112;
reg   [31:0] ap_phi_mux_k_3_phi_fu_246_p4;
reg   [31:0] k_0_reg_124;
reg   [31:0] ap_phi_mux_u_0_3_4_phi_fu_259_p4;
reg   [31:0] u_0_0_reg_136;
reg  signed [31:0] k_1_reg_148;
wire    ap_CS_fsm_state3;
wire   [0:0] and_ln14_fu_305_p2;
reg   [31:0] ap_phi_mux_u_0_2_phi_fu_220_p4;
reg   [31:0] u_reg_159;
reg   [31:0] u_0_3_reg_170;
reg   [31:0] count_0_reg_182;
reg   [30:0] j_0_reg_194;
wire   [31:0] k_4_fu_450_p2;
reg   [31:0] ap_phi_mux_k_2_phi_fu_208_p4;
reg   [31:0] k_2_reg_205;
wire   [31:0] u_0_fu_443_p2;
reg   [31:0] u_0_2_reg_215;
reg   [0:0] flag_1_reg_228;
reg   [31:0] k_3_reg_242;
reg   [31:0] u_0_3_4_reg_254;
wire   [63:0] zext_ln11_fu_283_p1;
wire  signed [63:0] sext_ln16_fu_311_p1;
wire   [63:0] zext_ln20_fu_338_p1;
wire  signed [63:0] sext_ln37_fu_438_p1;
reg   [31:0] sol_list_1_fu_52;
wire   [31:0] sol_list_fu_469_p2;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln14_fu_299_p2;
wire   [0:0] xor_ln14_fu_293_p2;
wire   [31:0] sub_ln20_fu_361_p2;
wire   [0:0] abscond_fu_373_p2;
wire   [31:0] neg_fu_367_p2;
wire   [31:0] abs_fu_379_p3;
wire   [31:0] sub_ln20_1_fu_387_p2;
wire   [0:0] icmp_ln20_1_fu_392_p2;
wire   [31:0] count_fu_398_p2;
wire   [0:0] icmp_ln20_fu_355_p2;
wire   [31:0] select_ln20_fu_404_p3;
reg   [9:0] ap_NS_fsm;
wire   [31:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
end

nqueens_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
nqueens_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(sol_list_1_fu_52)
);

nqueens_a #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(a_address0),
    .ce0(a_ce0),
    .we0(a_we0),
    .d0(a_d0),
    .q0(a_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_fu_316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        count_0_reg_182 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        count_0_reg_182 <= select_ln20_1_fu_412_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        flag_0_reg_101 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln42_fu_463_p2 == 1'd1) | ((icmp_ln33_reg_553 == 1'd1) & (icmp_ln31_reg_544 == 1'd1))))) begin
        flag_0_reg_101 <= ap_phi_mux_flag_1_phi_fu_233_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_432_p2 == 1'd1) & (icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        flag_1_reg_228 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        flag_1_reg_228 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        iteration_0_reg_112 <= 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln42_fu_463_p2 == 1'd1) | ((icmp_ln33_reg_553 == 1'd1) & (icmp_ln31_reg_544 == 1'd1))))) begin
        iteration_0_reg_112 <= iteration_fu_480_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_fu_316_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        j_0_reg_194 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        j_0_reg_194 <= j_reg_521;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_0_reg_124 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln42_fu_463_p2 == 1'd1) | ((icmp_ln33_reg_553 == 1'd1) & (icmp_ln31_reg_544 == 1'd1))))) begin
        k_0_reg_124 <= ap_phi_mux_k_3_phi_fu_246_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln14_fu_305_p2) & (1'b1 == ap_CS_fsm_state3))) begin
        k_1_reg_148 <= k_0_reg_124;
    end else if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd0) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd0) & (icmp_ln33_reg_553 == 1'd0))))) begin
        k_1_reg_148 <= k_5_fu_457_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln31_fu_420_p2 == 1'd0))) begin
        k_2_reg_205 <= k_1_reg_148;
    end else if (((icmp_ln31_reg_544 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln33_reg_553 == 1'd0))) begin
        k_2_reg_205 <= k_4_fu_450_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_432_p2 == 1'd1) & (icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        k_3_reg_242 <= k_fu_426_p2;
    end else if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        k_3_reg_242 <= 32'd8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        sol_list_1_fu_52 <= sol_list_fu_469_p2;
    end else if (((icmp_ln10_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        sol_list_1_fu_52 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        u_0_0_reg_136 <= 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln42_fu_463_p2 == 1'd1) | ((icmp_ln33_reg_553 == 1'd1) & (icmp_ln31_reg_544 == 1'd1))))) begin
        u_0_0_reg_136 <= ap_phi_mux_u_0_3_4_phi_fu_259_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln31_fu_420_p2 == 1'd0))) begin
        u_0_2_reg_215 <= 32'd1;
    end else if (((icmp_ln31_reg_544 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln33_reg_553 == 1'd0))) begin
        u_0_2_reg_215 <= u_0_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_432_p2 == 1'd1) & (icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        u_0_3_4_reg_254 <= 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        u_0_3_4_reg_254 <= ap_phi_mux_u_0_2_phi_fu_220_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln24_fu_343_p2 == 1'd0) & (icmp_ln19_fu_326_p2 == 1'd0))) begin
        u_0_3_reg_170 <= u_1_fu_349_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        u_0_3_reg_170 <= u_reg_159;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln14_fu_305_p2) & (1'b1 == ap_CS_fsm_state3))) begin
        u_reg_159 <= u_0_0_reg_136;
    end else if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd0) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd0) & (icmp_ln33_reg_553 == 1'd0))))) begin
        u_reg_159 <= ap_phi_mux_u_0_2_phi_fu_220_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln10_fu_271_p2 == 1'd0))) begin
        x_0_reg_90 <= x_fu_277_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        x_0_reg_90 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_addr_1_reg_504 <= sext_ln16_fu_311_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln17_reg_509 <= icmp_ln17_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln31_reg_544 <= icmp_ln31_fu_420_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        icmp_ln33_reg_553 <= icmp_ln33_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        j_reg_521 <= j_fu_332_p2;
        zext_ln19_reg_513[30 : 0] <= zext_ln19_fu_322_p1[30 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln33_fu_432_p2 == 1'd0))) begin
        a_address0 = sext_ln37_fu_438_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) | ((icmp_ln24_fu_343_p2 == 1'd1) & (icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln19_fu_326_p2 == 1'd0)))) begin
        a_address0 = a_addr_1_reg_504;
    end else if (((icmp_ln19_fu_326_p2 == 1'd1) & (icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        a_address0 = zext_ln20_fu_338_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a_address0 = sext_ln16_fu_311_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        a_address0 = zext_ln11_fu_283_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | ((icmp_ln24_fu_343_p2 == 1'd1) & (icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln19_fu_326_p2 == 1'd0)) | ((icmp_ln19_fu_326_p2 == 1'd1) & (icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6)) | ((icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln33_fu_432_p2 == 1'd0)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_fu_343_p2 == 1'd1) & (icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln19_fu_326_p2 == 1'd0))) begin
        a_d0 = u_0_3_reg_170;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln33_fu_432_p2 == 1'd0)))) begin
        a_d0 = 32'd0;
    end else begin
        a_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((icmp_ln24_fu_343_p2 == 1'd1) & (icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln19_fu_326_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln10_fu_271_p2 == 1'd0)) | ((icmp_ln31_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln33_fu_432_p2 == 1'd0)))) begin
        a_we0 = 1'b1;
    end else begin
        a_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == and_ln14_fu_305_p2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        ap_phi_mux_flag_1_phi_fu_233_p4 = 1'd0;
    end else begin
        ap_phi_mux_flag_1_phi_fu_233_p4 = flag_1_reg_228;
    end
end

always @ (*) begin
    if (((icmp_ln31_reg_544 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln33_reg_553 == 1'd0))) begin
        ap_phi_mux_k_2_phi_fu_208_p4 = k_4_fu_450_p2;
    end else begin
        ap_phi_mux_k_2_phi_fu_208_p4 = k_2_reg_205;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        ap_phi_mux_k_3_phi_fu_246_p4 = 32'd8;
    end else begin
        ap_phi_mux_k_3_phi_fu_246_p4 = k_3_reg_242;
    end
end

always @ (*) begin
    if (((icmp_ln31_reg_544 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln33_reg_553 == 1'd0))) begin
        ap_phi_mux_u_0_2_phi_fu_220_p4 = u_0_fu_443_p2;
    end else begin
        ap_phi_mux_u_0_2_phi_fu_220_p4 = u_0_2_reg_215;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln31_reg_544 == 1'd0)) | ((icmp_ln42_fu_463_p2 == 1'd1) & (icmp_ln33_reg_553 == 1'd0))))) begin
        ap_phi_mux_u_0_3_4_phi_fu_259_p4 = ap_phi_mux_u_0_2_phi_fu_220_p4;
    end else begin
        ap_phi_mux_u_0_3_4_phi_fu_259_p4 = u_0_3_4_reg_254;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == and_ln14_fu_305_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln10_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == and_ln14_fu_305_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln17_reg_509 == 1'd0) | ((icmp_ln24_fu_343_p2 == 1'd1) & (icmp_ln19_fu_326_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((icmp_ln17_reg_509 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln24_fu_343_p2 == 1'd0) & (icmp_ln19_fu_326_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln42_fu_463_p2 == 1'd1) | ((icmp_ln33_reg_553 == 1'd1) & (icmp_ln31_reg_544 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_fu_379_p3 = ((abscond_fu_373_p2[0:0] === 1'b1) ? sub_ln20_fu_361_p2 : neg_fu_367_p2);

assign abscond_fu_373_p2 = (($signed(sub_ln20_fu_361_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign and_ln14_fu_305_p2 = (xor_ln14_fu_293_p2 & icmp_ln14_fu_299_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign count_fu_398_p2 = (count_0_reg_182 + 32'd1);

assign icmp_ln10_fu_271_p2 = ((x_0_reg_90 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_299_p2 = (($signed(iteration_0_reg_112) < $signed(32'd1000)) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_316_p2 = (($signed(u_0_3_reg_170) < $signed(32'd9)) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_326_p2 = (($signed(zext_ln19_fu_322_p1) < $signed(k_1_reg_148)) ? 1'b1 : 1'b0);

assign icmp_ln20_1_fu_392_p2 = ((abs_fu_379_p3 == sub_ln20_1_fu_387_p2) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_355_p2 = ((u_0_3_reg_170 == a_q0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_343_p2 = ((count_0_reg_182 == k_1_reg_148) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_420_p2 = ((a_q0 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_432_p2 = ((k_1_reg_148 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_463_p2 = ((k_5_fu_457_p2 == 32'd8) ? 1'b1 : 1'b0);

assign iteration_fu_480_p2 = (iteration_0_reg_112 + 32'd1);

assign j_fu_332_p2 = (j_0_reg_194 + 31'd1);

assign k_4_fu_450_p2 = ($signed(k_1_reg_148) + $signed(32'd4294967294));

assign k_5_fu_457_p2 = (ap_phi_mux_k_2_phi_fu_208_p4 + 32'd1);

assign k_fu_426_p2 = ($signed(k_1_reg_148) + $signed(32'd4294967295));

assign neg_fu_367_p2 = (32'd0 - sub_ln20_fu_361_p2);

assign select_ln20_1_fu_412_p3 = ((icmp_ln20_fu_355_p2[0:0] === 1'b1) ? count_0_reg_182 : select_ln20_fu_404_p3);

assign select_ln20_fu_404_p3 = ((icmp_ln20_1_fu_392_p2[0:0] === 1'b1) ? count_0_reg_182 : count_fu_398_p2);

assign sext_ln16_fu_311_p1 = k_1_reg_148;

assign sext_ln37_fu_438_p1 = k_fu_426_p2;

assign sol_list_fu_469_p2 = (sol_list_1_fu_52 + 32'd1);

assign sub_ln20_1_fu_387_p2 = ($signed(k_1_reg_148) - $signed(zext_ln19_reg_513));

assign sub_ln20_fu_361_p2 = (u_0_3_reg_170 - a_q0);

assign u_0_fu_443_p2 = (a_q0 + 32'd1);

assign u_1_fu_349_p2 = (u_0_3_reg_170 + 32'd1);

assign x_fu_277_p2 = (x_0_reg_90 + 4'd1);

assign xor_ln14_fu_293_p2 = (flag_0_reg_101 ^ 1'd1);

assign zext_ln11_fu_283_p1 = x_0_reg_90;

assign zext_ln19_fu_322_p1 = j_0_reg_194;

assign zext_ln20_fu_338_p1 = j_0_reg_194;

always @ (posedge ap_clk) begin
    zext_ln19_reg_513[31] <= 1'b0;
end

endmodule //nqueens
