// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "find_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic find_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic find_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> find_0::ap_ST_fsm_state1 = "1";
const sc_lv<4> find_0::ap_ST_fsm_state2 = "10";
const sc_lv<4> find_0::ap_ST_fsm_state3 = "100";
const sc_lv<4> find_0::ap_ST_fsm_state4 = "1000";
const sc_lv<32> find_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> find_0::ap_const_lv32_1 = "1";
const sc_lv<1> find_0::ap_const_lv1_0 = "0";
const sc_lv<4> find_0::ap_const_lv4_0 = "0000";
const sc_lv<32> find_0::ap_const_lv32_2 = "10";
const sc_lv<4> find_0::ap_const_lv4_8 = "1000";
const sc_lv<1> find_0::ap_const_lv1_1 = "1";
const sc_lv<4> find_0::ap_const_lv4_1 = "1";
const sc_lv<32> find_0::ap_const_lv32_3 = "11";
const bool find_0::ap_const_boolean_1 = true;

find_0::find_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln8_fu_89_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( p_0_reg_65 );
    sensitive << ( ap_return_preg );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_i_fu_83_p2);
    sensitive << ( i_0_reg_53 );

    SC_METHOD(thread_icmp_ln6_fu_77_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_53 );

    SC_METHOD(thread_icmp_ln8_fu_94_p2);
    sensitive << ( a_q0 );
    sensitive << ( icmp_ln6_reg_100 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_zext_ln8_fu_89_p1);
    sensitive << ( i_0_reg_53 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln6_reg_100 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln8_fu_94_p2 );

    ap_CS_fsm = "0001";
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "find_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, icmp_ln6_fu_77_p2, "icmp_ln6_fu_77_p2");
    sc_trace(mVcdFile, icmp_ln6_reg_100, "icmp_ln6_reg_100");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_83_p2, "i_fu_83_p2");
    sc_trace(mVcdFile, i_reg_104, "i_reg_104");
    sc_trace(mVcdFile, i_0_reg_53, "i_0_reg_53");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln8_fu_94_p2, "icmp_ln8_fu_94_p2");
    sc_trace(mVcdFile, p_0_reg_65, "p_0_reg_65");
    sc_trace(mVcdFile, zext_ln8_fu_89_p1, "zext_ln8_fu_89_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

find_0::~find_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void find_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_return_preg = p_0_reg_65.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln6_reg_100.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln8_fu_94_p2.read()))) {
        i_0_reg_53 = i_reg_104.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_53 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln6_reg_100.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_94_p2.read(), ap_const_lv1_1))) {
        p_0_reg_65 = i_0_reg_53.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln6_fu_77_p2.read(), ap_const_lv1_1))) {
        p_0_reg_65 = ap_const_lv4_8;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_104 = i_fu_83_p2.read();
        icmp_ln6_reg_100 = icmp_ln6_fu_77_p2.read();
    }
}

void find_0::thread_a_address0() {
    a_address0 =  (sc_lv<3>) (zext_ln8_fu_89_p1.read());
}

void find_0::thread_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void find_0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void find_0::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void find_0::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void find_0::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void find_0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void find_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void find_0::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void find_0::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_return = p_0_reg_65.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void find_0::thread_i_fu_83_p2() {
    i_fu_83_p2 = (!i_0_reg_53.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_53.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void find_0::thread_icmp_ln6_fu_77_p2() {
    icmp_ln6_fu_77_p2 = (!i_0_reg_53.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_53.read() == ap_const_lv4_8);
}

void find_0::thread_icmp_ln8_fu_94_p2() {
    icmp_ln8_fu_94_p2 = (!a_q0.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(a_q0.read() == ap_const_lv32_0);
}

void find_0::thread_zext_ln8_fu_89_p1() {
    zext_ln8_fu_89_p1 = esl_zext<64,4>(i_0_reg_53.read());
}

void find_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln6_reg_100.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln8_fu_94_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

