// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "nqueens.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic nqueens::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic nqueens::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> nqueens::ap_ST_fsm_state1 = "1";
const sc_lv<7> nqueens::ap_ST_fsm_state2 = "10";
const sc_lv<7> nqueens::ap_ST_fsm_state3 = "100";
const sc_lv<7> nqueens::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<7> nqueens::ap_ST_fsm_state6 = "10000";
const sc_lv<7> nqueens::ap_ST_fsm_state7 = "100000";
const sc_lv<7> nqueens::ap_ST_fsm_state8 = "1000000";
const sc_lv<32> nqueens::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool nqueens::ap_const_boolean_1 = true;
const int nqueens::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> nqueens::ap_const_lv32_1 = "1";
const sc_lv<32> nqueens::ap_const_lv32_2 = "10";
const sc_lv<32> nqueens::ap_const_lv32_3 = "11";
const bool nqueens::ap_const_boolean_0 = false;
const sc_lv<1> nqueens::ap_const_lv1_1 = "1";
const sc_lv<32> nqueens::ap_const_lv32_4 = "100";
const sc_lv<1> nqueens::ap_const_lv1_0 = "0";
const sc_lv<31> nqueens::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> nqueens::ap_const_lv32_6 = "110";
const sc_lv<32> nqueens::ap_const_lv32_5 = "101";
const sc_lv<32> nqueens::ap_const_lv32_9 = "1001";
const sc_lv<31> nqueens::ap_const_lv31_1 = "1";
const sc_lv<32> nqueens::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> nqueens::ap_const_lv32_FFFFFFFE = "11111111111111111111111111111110";
const sc_lv<32> nqueens::ap_const_lv32_8 = "1000";

nqueens::nqueens(sc_module_name name) : sc_module(name), mVcdFile(0) {
    nqueens_AXILiteS_s_axi_U = new nqueens_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("nqueens_AXILiteS_s_axi_U");
    nqueens_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    nqueens_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    nqueens_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    nqueens_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    nqueens_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    nqueens_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    nqueens_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    nqueens_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    nqueens_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    nqueens_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    nqueens_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    nqueens_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    nqueens_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    nqueens_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    nqueens_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    nqueens_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    nqueens_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    nqueens_AXILiteS_s_axi_U->ACLK(ap_clk);
    nqueens_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    nqueens_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    nqueens_AXILiteS_s_axi_U->ap_start(ap_start);
    nqueens_AXILiteS_s_axi_U->interrupt(interrupt);
    nqueens_AXILiteS_s_axi_U->ap_ready(ap_ready);
    nqueens_AXILiteS_s_axi_U->ap_done(ap_done);
    nqueens_AXILiteS_s_axi_U->ap_idle(ap_idle);
    nqueens_AXILiteS_s_axi_U->a_address0(a_address0);
    nqueens_AXILiteS_s_axi_U->a_ce0(a_ce0);
    nqueens_AXILiteS_s_axi_U->a_we0(a_we0);
    nqueens_AXILiteS_s_axi_U->a_d0(a_d0);
    nqueens_AXILiteS_s_axi_U->a_q0(a_q0);
    nqueens_AXILiteS_s_axi_U->k_o(add_ln44_fu_358_p2);
    nqueens_AXILiteS_s_axi_U->k_o_ap_vld(k_o_ap_vld);
    nqueens_AXILiteS_s_axi_U->k_i(k_i);
    nqueens_AXILiteS_s_axi_U->u_0_o(u_0_o);
    nqueens_AXILiteS_s_axi_U->u_0_o_ap_vld(u_0_o_ap_vld);
    nqueens_AXILiteS_s_axi_U->u_0_i(u_0_i);
    nqueens_AXILiteS_s_axi_U->sol_list_o(sol_list_o);
    nqueens_AXILiteS_s_axi_U->sol_list_o_ap_vld(sol_list_o_ap_vld);
    nqueens_AXILiteS_s_axi_U->sol_list_i(sol_list_i);
    nqueens_AXILiteS_s_axi_U->flag(ap_var_for_const1);
    nqueens_AXILiteS_s_axi_U->flag_ap_vld(flag_ap_vld);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( a_addr_1_reg_438 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln11_fu_240_p1 );
    sensitive << ( sext_ln32_fu_320_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_a_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_phi_mux_p_0_i_phi_fu_176_p4 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_a_we0);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_abs_i_fu_269_p3);
    sensitive << ( sub_ln11_fu_251_p2 );
    sensitive << ( abscond_i_fu_263_p2 );
    sensitive << ( neg_i_fu_257_p2 );

    SC_METHOD(thread_abscond_i_fu_263_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln9_reg_404 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sub_ln11_fu_251_p2 );

    SC_METHOD(thread_add_ln35_fu_330_p2);
    sensitive << ( k_read_reg_378 );

    SC_METHOD(thread_add_ln40_fu_345_p2);
    sensitive << ( a_q0 );

    SC_METHOD(thread_add_ln42_fu_352_p2);
    sensitive << ( k_read_reg_378 );

    SC_METHOD(thread_add_ln44_fu_358_p2);
    sensitive << ( ap_phi_mux_empty_3_phi_fu_201_p4 );

    SC_METHOD(thread_add_ln46_fu_371_p2);
    sensitive << ( sol_list_i );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_199);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_fu_324_p2 );
    sensitive << ( icmp_ln36_fu_335_p2 );

    SC_METHOD(thread_ap_condition_204);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_fu_324_p2 );
    sensitive << ( icmp_ln36_fu_335_p2 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( icmp_ln9_fu_229_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_phi_mux_exit_2_phi_fu_211_p4 );
    sensitive << ( icmp_ln45_fu_365_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_empty_3_phi_fu_201_p4);
    sensitive << ( icmp_ln34_reg_431 );
    sensitive << ( add_ln42_fu_352_p2 );
    sensitive << ( empty_3_reg_198 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_phi_mux_exit_2_phi_fu_211_p4);
    sensitive << ( icmp_ln34_reg_431 );
    sensitive << ( exit_1_reg_185 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exit_2_reg_207 );

    SC_METHOD(thread_ap_phi_mux_p_0_i_phi_fu_176_p4);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( u_0_i_reg_139 );
    sensitive << ( p_0_i_reg_172 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_phi_mux_exit_2_phi_fu_211_p4 );
    sensitive << ( icmp_ln45_fu_365_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_count_fu_287_p2);
    sensitive << ( count_0_i_reg_149 );

    SC_METHOD(thread_flag_ap_vld);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_fu_324_p2 );
    sensitive << ( icmp_ln36_fu_335_p2 );

    SC_METHOD(thread_icmp_ln11_1_fu_281_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln9_reg_404 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( abs_i_fu_269_p3 );
    sensitive << ( sub_ln11_1_fu_277_p2 );

    SC_METHOD(thread_icmp_ln11_fu_245_p2);
    sensitive << ( a_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln9_reg_404 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( u_0_i_reg_139 );

    SC_METHOD(thread_icmp_ln15_fu_309_p2);
    sensitive << ( count_0_i_reg_149 );
    sensitive << ( k_read_reg_378 );
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln34_fu_324_p2);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( ap_phi_mux_p_0_i_phi_fu_176_p4 );

    SC_METHOD(thread_icmp_ln36_fu_335_p2);
    sensitive << ( k_read_reg_378 );
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_fu_324_p2 );

    SC_METHOD(thread_icmp_ln45_fu_365_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( add_ln44_fu_358_p2 );

    SC_METHOD(thread_icmp_ln7_fu_219_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( u_0_i_reg_139 );

    SC_METHOD(thread_icmp_ln9_fu_229_p2);
    sensitive << ( k_read_reg_378 );
    sensitive << ( zext_ln9_fu_225_p1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_j_fu_234_p2);
    sensitive << ( j_0_i_reg_161 );

    SC_METHOD(thread_k_o_ap_vld);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_neg_i_fu_257_p2);
    sensitive << ( sub_ln11_fu_251_p2 );

    SC_METHOD(thread_select_ln11_1_fu_301_p3);
    sensitive << ( count_0_i_reg_149 );
    sensitive << ( icmp_ln11_fu_245_p2 );
    sensitive << ( select_ln11_fu_293_p3 );

    SC_METHOD(thread_select_ln11_fu_293_p3);
    sensitive << ( count_0_i_reg_149 );
    sensitive << ( icmp_ln11_1_fu_281_p2 );
    sensitive << ( count_fu_287_p2 );

    SC_METHOD(thread_sext_ln32_fu_320_p1);
    sensitive << ( k_read_reg_378 );

    SC_METHOD(thread_sext_ln40_fu_340_p1);
    sensitive << ( add_ln35_fu_330_p2 );

    SC_METHOD(thread_sol_list_o);
    sensitive << ( sol_list_i );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln45_fu_365_p2 );
    sensitive << ( add_ln46_fu_371_p2 );

    SC_METHOD(thread_sol_list_o_ap_vld);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln45_fu_365_p2 );

    SC_METHOD(thread_sub_ln11_1_fu_277_p2);
    sensitive << ( k_read_reg_378 );
    sensitive << ( zext_ln9_reg_399 );

    SC_METHOD(thread_sub_ln11_fu_251_p2);
    sensitive << ( a_q0 );
    sensitive << ( u_0_i_reg_139 );

    SC_METHOD(thread_u_0_o);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_reg_431 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( add_ln40_fu_345_p2 );

    SC_METHOD(thread_u_0_o_ap_vld);
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_reg_431 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_u_1_fu_314_p2);
    sensitive << ( u_0_i_reg_139 );

    SC_METHOD(thread_zext_ln11_fu_240_p1);
    sensitive << ( j_0_i_reg_161 );

    SC_METHOD(thread_zext_ln9_fu_225_p1);
    sensitive << ( j_0_i_reg_161 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln7_fu_219_p2 );
    sensitive << ( icmp_ln7_reg_395 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln9_fu_229_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln15_fu_309_p2 );
    sensitive << ( icmp_ln34_fu_324_p2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_phi_mux_exit_2_phi_fu_211_p4 );
    sensitive << ( icmp_ln45_fu_365_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "nqueens_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, a_address0, "a_address0");
    sc_trace(mVcdFile, a_ce0, "a_ce0");
    sc_trace(mVcdFile, a_we0, "a_we0");
    sc_trace(mVcdFile, a_d0, "a_d0");
    sc_trace(mVcdFile, a_q0, "a_q0");
    sc_trace(mVcdFile, k_i, "k_i");
    sc_trace(mVcdFile, k_o_ap_vld, "k_o_ap_vld");
    sc_trace(mVcdFile, u_0_i, "u_0_i");
    sc_trace(mVcdFile, u_0_o, "u_0_o");
    sc_trace(mVcdFile, u_0_o_ap_vld, "u_0_o_ap_vld");
    sc_trace(mVcdFile, sol_list_i, "sol_list_i");
    sc_trace(mVcdFile, sol_list_o, "sol_list_o");
    sc_trace(mVcdFile, sol_list_o_ap_vld, "sol_list_o_ap_vld");
    sc_trace(mVcdFile, flag_ap_vld, "flag_ap_vld");
    sc_trace(mVcdFile, count_0_i_reg_149, "count_0_i_reg_149");
    sc_trace(mVcdFile, j_0_i_reg_161, "j_0_i_reg_161");
    sc_trace(mVcdFile, k_read_reg_378, "k_read_reg_378");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln7_fu_219_p2, "icmp_ln7_fu_219_p2");
    sc_trace(mVcdFile, icmp_ln7_reg_395, "icmp_ln7_reg_395");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln9_fu_225_p1, "zext_ln9_fu_225_p1");
    sc_trace(mVcdFile, zext_ln9_reg_399, "zext_ln9_reg_399");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln9_fu_229_p2, "icmp_ln9_fu_229_p2");
    sc_trace(mVcdFile, icmp_ln9_reg_404, "icmp_ln9_reg_404");
    sc_trace(mVcdFile, j_fu_234_p2, "j_fu_234_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln11_1_fu_301_p3, "select_ln11_1_fu_301_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, u_1_fu_314_p2, "u_1_fu_314_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln15_fu_309_p2, "icmp_ln15_fu_309_p2");
    sc_trace(mVcdFile, icmp_ln34_fu_324_p2, "icmp_ln34_fu_324_p2");
    sc_trace(mVcdFile, icmp_ln34_reg_431, "icmp_ln34_reg_431");
    sc_trace(mVcdFile, a_addr_1_reg_438, "a_addr_1_reg_438");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, u_0_i_reg_139, "u_0_i_reg_139");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_p_0_i_phi_fu_176_p4, "ap_phi_mux_p_0_i_phi_fu_176_p4");
    sc_trace(mVcdFile, p_0_i_reg_172, "p_0_i_reg_172");
    sc_trace(mVcdFile, exit_1_reg_185, "exit_1_reg_185");
    sc_trace(mVcdFile, icmp_ln36_fu_335_p2, "icmp_ln36_fu_335_p2");
    sc_trace(mVcdFile, add_ln42_fu_352_p2, "add_ln42_fu_352_p2");
    sc_trace(mVcdFile, ap_phi_mux_empty_3_phi_fu_201_p4, "ap_phi_mux_empty_3_phi_fu_201_p4");
    sc_trace(mVcdFile, empty_3_reg_198, "empty_3_reg_198");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_phi_mux_exit_2_phi_fu_211_p4, "ap_phi_mux_exit_2_phi_fu_211_p4");
    sc_trace(mVcdFile, exit_2_reg_207, "exit_2_reg_207");
    sc_trace(mVcdFile, zext_ln11_fu_240_p1, "zext_ln11_fu_240_p1");
    sc_trace(mVcdFile, sext_ln32_fu_320_p1, "sext_ln32_fu_320_p1");
    sc_trace(mVcdFile, sext_ln40_fu_340_p1, "sext_ln40_fu_340_p1");
    sc_trace(mVcdFile, add_ln40_fu_345_p2, "add_ln40_fu_345_p2");
    sc_trace(mVcdFile, add_ln44_fu_358_p2, "add_ln44_fu_358_p2");
    sc_trace(mVcdFile, icmp_ln45_fu_365_p2, "icmp_ln45_fu_365_p2");
    sc_trace(mVcdFile, add_ln46_fu_371_p2, "add_ln46_fu_371_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sub_ln11_fu_251_p2, "sub_ln11_fu_251_p2");
    sc_trace(mVcdFile, abscond_i_fu_263_p2, "abscond_i_fu_263_p2");
    sc_trace(mVcdFile, neg_i_fu_257_p2, "neg_i_fu_257_p2");
    sc_trace(mVcdFile, abs_i_fu_269_p3, "abs_i_fu_269_p3");
    sc_trace(mVcdFile, sub_ln11_1_fu_277_p2, "sub_ln11_1_fu_277_p2");
    sc_trace(mVcdFile, icmp_ln11_1_fu_281_p2, "icmp_ln11_1_fu_281_p2");
    sc_trace(mVcdFile, count_fu_287_p2, "count_fu_287_p2");
    sc_trace(mVcdFile, icmp_ln11_fu_245_p2, "icmp_ln11_fu_245_p2");
    sc_trace(mVcdFile, select_ln11_fu_293_p3, "select_ln11_fu_293_p3");
    sc_trace(mVcdFile, add_ln35_fu_330_p2, "add_ln35_fu_330_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_199, "ap_condition_199");
    sc_trace(mVcdFile, ap_condition_204, "ap_condition_204");
#endif

    }
    mHdltvinHandle.open("nqueens.hdltvin.dat");
    mHdltvoutHandle.open("nqueens.hdltvout.dat");
}

nqueens::~nqueens() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete nqueens_AXILiteS_s_axi_U;
}

void nqueens::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void nqueens::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_1;
}

void nqueens::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(icmp_ln7_fu_219_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(icmp_ln7_fu_219_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_219_p2.read(), ap_const_lv1_1))) {
        count_0_i_reg_149 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(icmp_ln9_reg_404.read(), ap_const_lv1_1))) {
        count_0_i_reg_149 = select_ln11_1_fu_301_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_324_p2.read())) || 
          (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_324_p2.read()))))) {
        empty_3_reg_198 = k_read_reg_378.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_reg_431.read()))) {
        empty_3_reg_198 = add_ln42_fu_352_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        if (esl_seteq<1,1,1>(ap_condition_204.read(), ap_const_boolean_1)) {
            exit_1_reg_185 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_condition_199.read(), ap_const_boolean_1)) {
            exit_1_reg_185 = ap_const_lv1_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_324_p2.read())) || 
          (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_324_p2.read()))))) {
        exit_2_reg_207 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_reg_431.read()))) {
        exit_2_reg_207 = exit_1_reg_185.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_219_p2.read(), ap_const_lv1_1))) {
        j_0_i_reg_161 = ap_const_lv31_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(icmp_ln9_fu_229_p2.read(), ap_const_lv1_1))) {
        j_0_i_reg_161 = j_fu_234_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()))) {
        p_0_i_reg_172 = u_0_i_reg_139.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln7_fu_219_p2.read(), ap_const_lv1_0))) {
        p_0_i_reg_172 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_309_p2.read(), ap_const_lv1_0))) {
        u_0_i_reg_139 = u_1_fu_314_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        u_0_i_reg_139 = u_0_i.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()))))) {
        a_addr_1_reg_438 =  (sc_lv<3>) (sext_ln40_fu_340_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) || 
  esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0)))) {
        icmp_ln34_reg_431 = icmp_ln34_fu_324_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        icmp_ln7_reg_395 = icmp_ln7_fu_219_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln9_reg_404 = icmp_ln9_fu_229_p2.read();
        zext_ln9_reg_399 = zext_ln9_fu_225_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        k_read_reg_378 = k_i.read();
    }
}

void nqueens::thread_a_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        a_address0 = a_addr_1_reg_438.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        a_address0 =  (sc_lv<3>) (sext_ln32_fu_320_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        a_address0 =  (sc_lv<3>) (zext_ln11_fu_240_p1.read());
    } else {
        a_address0 = "XXX";
    }
}

void nqueens::thread_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void nqueens::thread_a_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        a_d0 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        a_d0 = ap_phi_mux_p_0_i_phi_fu_176_p4.read();
    } else {
        a_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nqueens::thread_a_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) || 
           esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        a_we0 = ap_const_logic_1;
    } else {
        a_we0 = ap_const_logic_0;
    }
}

void nqueens::thread_abs_i_fu_269_p3() {
    abs_i_fu_269_p3 = (!abscond_i_fu_263_p2.read()[0].is_01())? sc_lv<32>(): ((abscond_i_fu_263_p2.read()[0].to_bool())? sub_ln11_fu_251_p2.read(): neg_i_fu_257_p2.read());
}

void nqueens::thread_abscond_i_fu_263_p2() {
    abscond_i_fu_263_p2 = (!sub_ln11_fu_251_p2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(sub_ln11_fu_251_p2.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void nqueens::thread_add_ln35_fu_330_p2() {
    add_ln35_fu_330_p2 = (!k_read_reg_378.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_bigint<32>(k_read_reg_378.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void nqueens::thread_add_ln40_fu_345_p2() {
    add_ln40_fu_345_p2 = (!a_q0.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(a_q0.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void nqueens::thread_add_ln42_fu_352_p2() {
    add_ln42_fu_352_p2 = (!k_read_reg_378.read().is_01() || !ap_const_lv32_FFFFFFFE.is_01())? sc_lv<32>(): (sc_bigint<32>(k_read_reg_378.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFE));
}

void nqueens::thread_add_ln44_fu_358_p2() {
    add_ln44_fu_358_p2 = (!ap_phi_mux_empty_3_phi_fu_201_p4.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(ap_phi_mux_empty_3_phi_fu_201_p4.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void nqueens::thread_add_ln46_fu_371_p2() {
    add_ln46_fu_371_p2 = (!sol_list_i.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(sol_list_i.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void nqueens::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void nqueens::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void nqueens::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void nqueens::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void nqueens::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void nqueens::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void nqueens::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void nqueens::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void nqueens::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void nqueens::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void nqueens::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void nqueens::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void nqueens::thread_ap_condition_199() {
    ap_condition_199 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_335_p2.read())) || (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_335_p2.read())));
}

void nqueens::thread_ap_condition_204() {
    ap_condition_204 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_335_p2.read())) || (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_335_p2.read())));
}

void nqueens::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(icmp_ln9_fu_229_p2.read(), ap_const_lv1_0)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void nqueens::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_exit_2_phi_fu_211_p4.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln45_fu_365_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void nqueens::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void nqueens::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void nqueens::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void nqueens::thread_ap_phi_mux_empty_3_phi_fu_201_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_reg_431.read()))) {
        ap_phi_mux_empty_3_phi_fu_201_p4 = add_ln42_fu_352_p2.read();
    } else {
        ap_phi_mux_empty_3_phi_fu_201_p4 = empty_3_reg_198.read();
    }
}

void nqueens::thread_ap_phi_mux_exit_2_phi_fu_211_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_reg_431.read()))) {
        ap_phi_mux_exit_2_phi_fu_211_p4 = exit_1_reg_185.read();
    } else {
        ap_phi_mux_exit_2_phi_fu_211_p4 = exit_2_reg_207.read();
    }
}

void nqueens::thread_ap_phi_mux_p_0_i_phi_fu_176_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()))) {
        ap_phi_mux_p_0_i_phi_fu_176_p4 = u_0_i_reg_139.read();
    } else {
        ap_phi_mux_p_0_i_phi_fu_176_p4 = p_0_i_reg_172.read();
    }
}

void nqueens::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_exit_2_phi_fu_211_p4.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln45_fu_365_p2.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void nqueens::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void nqueens::thread_count_fu_287_p2() {
    count_fu_287_p2 = (!count_0_i_reg_149.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(count_0_i_reg_149.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void nqueens::thread_flag_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_335_p2.read())) || 
          (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_335_p2.read()))))) {
        flag_ap_vld = ap_const_logic_1;
    } else {
        flag_ap_vld = ap_const_logic_0;
    }
}

void nqueens::thread_icmp_ln11_1_fu_281_p2() {
    icmp_ln11_1_fu_281_p2 = (!abs_i_fu_269_p3.read().is_01() || !sub_ln11_1_fu_277_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(abs_i_fu_269_p3.read() == sub_ln11_1_fu_277_p2.read());
}

void nqueens::thread_icmp_ln11_fu_245_p2() {
    icmp_ln11_fu_245_p2 = (!u_0_i_reg_139.read().is_01() || !a_q0.read().is_01())? sc_lv<1>(): sc_lv<1>(u_0_i_reg_139.read() == a_q0.read());
}

void nqueens::thread_icmp_ln15_fu_309_p2() {
    icmp_ln15_fu_309_p2 = (!count_0_i_reg_149.read().is_01() || !k_read_reg_378.read().is_01())? sc_lv<1>(): sc_lv<1>(count_0_i_reg_149.read() == k_read_reg_378.read());
}

void nqueens::thread_icmp_ln34_fu_324_p2() {
    icmp_ln34_fu_324_p2 = (!ap_phi_mux_p_0_i_phi_fu_176_p4.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_p_0_i_phi_fu_176_p4.read() == ap_const_lv32_0);
}

void nqueens::thread_icmp_ln36_fu_335_p2() {
    icmp_ln36_fu_335_p2 = (!k_read_reg_378.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(k_read_reg_378.read() == ap_const_lv32_0);
}

void nqueens::thread_icmp_ln45_fu_365_p2() {
    icmp_ln45_fu_365_p2 = (!add_ln44_fu_358_p2.read().is_01() || !ap_const_lv32_8.is_01())? sc_lv<1>(): sc_lv<1>(add_ln44_fu_358_p2.read() == ap_const_lv32_8);
}

void nqueens::thread_icmp_ln7_fu_219_p2() {
    icmp_ln7_fu_219_p2 = (!u_0_i_reg_139.read().is_01() || !ap_const_lv32_9.is_01())? sc_lv<1>(): (sc_bigint<32>(u_0_i_reg_139.read()) < sc_bigint<32>(ap_const_lv32_9));
}

void nqueens::thread_icmp_ln9_fu_229_p2() {
    icmp_ln9_fu_229_p2 = (!zext_ln9_fu_225_p1.read().is_01() || !k_read_reg_378.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln9_fu_225_p1.read()) < sc_bigint<32>(k_read_reg_378.read()));
}

void nqueens::thread_j_fu_234_p2() {
    j_fu_234_p2 = (!j_0_i_reg_161.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(j_0_i_reg_161.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void nqueens::thread_k_o_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        k_o_ap_vld = ap_const_logic_1;
    } else {
        k_o_ap_vld = ap_const_logic_0;
    }
}

void nqueens::thread_neg_i_fu_257_p2() {
    neg_i_fu_257_p2 = (!ap_const_lv32_0.is_01() || !sub_ln11_fu_251_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(sub_ln11_fu_251_p2.read()));
}

void nqueens::thread_select_ln11_1_fu_301_p3() {
    select_ln11_1_fu_301_p3 = (!icmp_ln11_fu_245_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln11_fu_245_p2.read()[0].to_bool())? count_0_i_reg_149.read(): select_ln11_fu_293_p3.read());
}

void nqueens::thread_select_ln11_fu_293_p3() {
    select_ln11_fu_293_p3 = (!icmp_ln11_1_fu_281_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln11_1_fu_281_p2.read()[0].to_bool())? count_0_i_reg_149.read(): count_fu_287_p2.read());
}

void nqueens::thread_sext_ln32_fu_320_p1() {
    sext_ln32_fu_320_p1 = esl_sext<64,32>(k_read_reg_378.read());
}

void nqueens::thread_sext_ln40_fu_340_p1() {
    sext_ln40_fu_340_p1 = esl_sext<64,32>(add_ln35_fu_330_p2.read());
}

void nqueens::thread_sol_list_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln45_fu_365_p2.read()))) {
        sol_list_o = add_ln46_fu_371_p2.read();
    } else {
        sol_list_o = sol_list_i.read();
    }
}

void nqueens::thread_sol_list_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln45_fu_365_p2.read()))) {
        sol_list_o_ap_vld = ap_const_logic_1;
    } else {
        sol_list_o_ap_vld = ap_const_logic_0;
    }
}

void nqueens::thread_sub_ln11_1_fu_277_p2() {
    sub_ln11_1_fu_277_p2 = (!k_read_reg_378.read().is_01() || !zext_ln9_reg_399.read().is_01())? sc_lv<32>(): (sc_bigint<32>(k_read_reg_378.read()) - sc_biguint<32>(zext_ln9_reg_399.read()));
}

void nqueens::thread_sub_ln11_fu_251_p2() {
    sub_ln11_fu_251_p2 = (!u_0_i_reg_139.read().is_01() || !a_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(u_0_i_reg_139.read()) - sc_biguint<32>(a_q0.read()));
}

void nqueens::thread_u_0_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_reg_431.read()))) {
        u_0_o = add_ln40_fu_345_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) || 
                 esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0)))) {
        u_0_o = ap_const_lv32_1;
    } else {
        u_0_o =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nqueens::thread_u_0_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) || 
           esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_reg_431.read())))) {
        u_0_o_ap_vld = ap_const_logic_1;
    } else {
        u_0_o_ap_vld = ap_const_logic_0;
    }
}

void nqueens::thread_u_1_fu_314_p2() {
    u_1_fu_314_p2 = (!u_0_i_reg_139.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(u_0_i_reg_139.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void nqueens::thread_zext_ln11_fu_240_p1() {
    zext_ln11_fu_240_p1 = esl_zext<64,31>(j_0_i_reg_161.read());
}

void nqueens::thread_zext_ln9_fu_225_p1() {
    zext_ln9_fu_225_p1 = esl_zext<32,31>(j_0_i_reg_161.read());
}

void nqueens::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_219_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln9_fu_229_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln9_fu_229_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln34_fu_324_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln15_fu_309_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_324_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln7_reg_395.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_324_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_exit_2_phi_fu_211_p4.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln45_fu_365_p2.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

void nqueens::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

