#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 25 20:41:05 -03 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_queens_tb_behav -key {Behavioral:sim_1:Functional:top_queens_tb} -tclbatch top_queens_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/agustinsilva447/Escritorio/Github/FPGA/pynq/pynq_nqueens_4/top_queens_tb_behav.wcfg -log simulate.log"
xsim top_queens_tb_behav -key {Behavioral:sim_1:Functional:top_queens_tb} -tclbatch top_queens_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/agustinsilva447/Escritorio/Github/FPGA/pynq/pynq_nqueens_4/top_queens_tb_behav.wcfg -log simulate.log

