// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_multiply_alt2_HH_
#define _matrix_multiply_alt2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matrix_multiply_tcud.h"
#include "matrix_multiply_tdEe.h"
#include "matrix_multiply_abkb.h"

namespace ap_rtl {

struct matrix_multiply_alt2 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > A_address0;
    sc_out< sc_logic > A_ce0;
    sc_in< sc_lv<32> > A_q0;
    sc_out< sc_lv<4> > B_address0;
    sc_out< sc_logic > B_ce0;
    sc_in< sc_lv<32> > B_q0;
    sc_out< sc_lv<4> > C_address0;
    sc_out< sc_logic > C_ce0;
    sc_out< sc_logic > C_we0;
    sc_out< sc_lv<32> > C_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    matrix_multiply_alt2(sc_module_name name);
    SC_HAS_PROCESS(matrix_multiply_alt2);

    ~matrix_multiply_alt2();

    sc_trace_file* mVcdFile;

    matrix_multiply_abkb* sum_mult_U;
    matrix_multiply_tcud<1,7,32,32,32>* matrix_multiply_tcud_U1;
    matrix_multiply_tdEe<1,6,32,32,32>* matrix_multiply_tdEe_U2;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > indvar_flatten14_reg_116;
    sc_signal< sc_lv<2> > Col_assign_2_reg_127;
    sc_signal< sc_lv<4> > indvar_flatten_reg_138;
    sc_signal< sc_lv<2> > Row_assign_reg_149;
    sc_signal< sc_lv<2> > Col_assign_reg_160;
    sc_signal< sc_lv<1> > icmp_ln318_fu_184_p2;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter7;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter8;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter9;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter10;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter11;
    sc_signal< bool > ap_block_state14_pp0_stage0_iter12;
    sc_signal< bool > ap_block_state15_pp0_stage0_iter13;
    sc_signal< bool > ap_block_state16_pp0_stage0_iter14;
    sc_signal< bool > ap_block_state17_pp0_stage0_iter15;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406_pp0_iter1_reg;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406_pp0_iter2_reg;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406_pp0_iter3_reg;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406_pp0_iter4_reg;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406_pp0_iter5_reg;
    sc_signal< sc_lv<1> > icmp_ln318_reg_406_pp0_iter6_reg;
    sc_signal< sc_lv<5> > add_ln318_fu_190_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > select_ln330_1_fu_228_p3;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter1_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter2_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter3_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter4_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter5_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter6_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter7_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter8_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter9_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter10_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter11_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter12_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter13_reg;
    sc_signal< sc_lv<1> > select_ln330_1_reg_415_pp0_iter14_reg;
    sc_signal< sc_lv<1> > select_ln330_2_fu_248_p3;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter1_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter2_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter3_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter4_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter5_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter6_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter7_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter8_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter9_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter10_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter11_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter12_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter13_reg;
    sc_signal< sc_lv<1> > select_ln330_2_reg_419_pp0_iter14_reg;
    sc_signal< sc_lv<2> > select_ln330_3_fu_256_p3;
    sc_signal< sc_lv<2> > select_ln330_3_reg_423;
    sc_signal< sc_lv<2> > select_ln332_fu_294_p3;
    sc_signal< sc_lv<2> > select_ln332_reg_430;
    sc_signal< sc_lv<2> > select_ln332_1_fu_302_p3;
    sc_signal< sc_lv<2> > select_ln332_1_reg_435;
    sc_signal< sc_lv<2> > c_fu_310_p2;
    sc_signal< sc_lv<4> > select_ln319_fu_322_p3;
    sc_signal< sc_lv<5> > add_ln335_fu_395_p2;
    sc_signal< sc_lv<5> > add_ln335_reg_462;
    sc_signal< sc_lv<5> > add_ln335_reg_462_pp0_iter2_reg;
    sc_signal< sc_lv<5> > add_ln335_reg_462_pp0_iter3_reg;
    sc_signal< sc_lv<5> > add_ln335_reg_462_pp0_iter4_reg;
    sc_signal< sc_lv<5> > add_ln335_reg_462_pp0_iter5_reg;
    sc_signal< sc_lv<5> > add_ln335_reg_462_pp0_iter6_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter8_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter9_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter10_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter11_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter12_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter13_reg;
    sc_signal< sc_lv<4> > C_addr_reg_477_pp0_iter14_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter8_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter9_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter10_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter11_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter12_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter13_reg;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_482_pp0_iter14_reg;
    sc_signal< sc_lv<32> > grp_fu_177_p2;
    sc_signal< sc_lv<32> > mult_reg_488;
    sc_signal< sc_lv<32> > mult_reg_488_pp0_iter8_reg;
    sc_signal< sc_lv<32> > sum_mult_q0;
    sc_signal< sc_lv<32> > sum_mult_load_reg_493;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter8;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter9;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter10;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter11;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter12;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter13;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter14;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter15;
    sc_signal< sc_lv<4> > sum_mult_address0;
    sc_signal< sc_logic > sum_mult_ce0;
    sc_signal< sc_logic > sum_mult_we0;
    sc_signal< sc_logic > sum_mult_ce1;
    sc_signal< sc_logic > sum_mult_we1;
    sc_signal< sc_lv<2> > ap_phi_mux_Col_assign_2_phi_fu_131_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<2> > ap_phi_mux_Row_assign_phi_fu_153_p4;
    sc_signal< sc_lv<64> > zext_ln60_3_fu_376_p1;
    sc_signal< sc_lv<64> > sext_ln60_fu_390_p1;
    sc_signal< sc_lv<64> > zext_ln335_fu_401_p1;
    sc_signal< sc_lv<32> > grp_fu_171_p2;
    sc_signal< sc_lv<1> > icmp_ln319_fu_202_p2;
    sc_signal< sc_lv<2> > k_fu_196_p2;
    sc_signal< sc_lv<1> > icmp_ln330_fu_216_p2;
    sc_signal< sc_lv<1> > icmp_ln330_1_fu_222_p2;
    sc_signal< sc_lv<1> > icmp_ln333_fu_236_p2;
    sc_signal< sc_lv<1> > icmp_ln333_1_fu_242_p2;
    sc_signal< sc_lv<1> > icmp_ln320_fu_270_p2;
    sc_signal< sc_lv<1> > xor_ln330_fu_264_p2;
    sc_signal< sc_lv<2> > select_ln330_fu_208_p3;
    sc_signal< sc_lv<1> > and_ln330_fu_276_p2;
    sc_signal< sc_lv<1> > or_ln332_fu_288_p2;
    sc_signal< sc_lv<2> > r_fu_282_p2;
    sc_signal< sc_lv<4> > add_ln319_fu_316_p2;
    sc_signal< sc_lv<4> > tmp_6_fu_333_p3;
    sc_signal< sc_lv<5> > zext_ln60_1_fu_340_p1;
    sc_signal< sc_lv<5> > zext_ln60_fu_330_p1;
    sc_signal< sc_lv<4> > tmp_1_fu_353_p3;
    sc_signal< sc_lv<5> > zext_ln60_2_fu_360_p1;
    sc_signal< sc_lv<5> > zext_ln332_fu_350_p1;
    sc_signal< sc_lv<5> > sub_ln60_1_fu_364_p2;
    sc_signal< sc_lv<5> > add_ln60_fu_370_p2;
    sc_signal< sc_lv<5> > zext_ln60_4_fu_381_p1;
    sc_signal< sc_lv<5> > sub_ln60_fu_344_p2;
    sc_signal< sc_lv<5> > add_ln60_1_fu_384_p2;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state18;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<5> ap_const_lv5_1B;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_A_address0();
    void thread_A_ce0();
    void thread_B_address0();
    void thread_B_ce0();
    void thread_C_address0();
    void thread_C_ce0();
    void thread_C_d0();
    void thread_C_we0();
    void thread_add_ln318_fu_190_p2();
    void thread_add_ln319_fu_316_p2();
    void thread_add_ln335_fu_395_p2();
    void thread_add_ln60_1_fu_384_p2();
    void thread_add_ln60_fu_370_p2();
    void thread_and_ln330_fu_276_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state18();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_pp0_stage0_iter8();
    void thread_ap_block_state11_pp0_stage0_iter9();
    void thread_ap_block_state12_pp0_stage0_iter10();
    void thread_ap_block_state13_pp0_stage0_iter11();
    void thread_ap_block_state14_pp0_stage0_iter12();
    void thread_ap_block_state15_pp0_stage0_iter13();
    void thread_ap_block_state16_pp0_stage0_iter14();
    void thread_ap_block_state17_pp0_stage0_iter15();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5_pp0_stage0_iter3();
    void thread_ap_block_state6_pp0_stage0_iter4();
    void thread_ap_block_state7_pp0_stage0_iter5();
    void thread_ap_block_state8_pp0_stage0_iter6();
    void thread_ap_block_state9_pp0_stage0_iter7();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_Col_assign_2_phi_fu_131_p4();
    void thread_ap_phi_mux_Row_assign_phi_fu_153_p4();
    void thread_ap_ready();
    void thread_c_fu_310_p2();
    void thread_icmp_ln318_fu_184_p2();
    void thread_icmp_ln319_fu_202_p2();
    void thread_icmp_ln320_fu_270_p2();
    void thread_icmp_ln330_1_fu_222_p2();
    void thread_icmp_ln330_fu_216_p2();
    void thread_icmp_ln333_1_fu_242_p2();
    void thread_icmp_ln333_fu_236_p2();
    void thread_k_fu_196_p2();
    void thread_or_ln332_fu_288_p2();
    void thread_r_fu_282_p2();
    void thread_select_ln319_fu_322_p3();
    void thread_select_ln330_1_fu_228_p3();
    void thread_select_ln330_2_fu_248_p3();
    void thread_select_ln330_3_fu_256_p3();
    void thread_select_ln330_fu_208_p3();
    void thread_select_ln332_1_fu_302_p3();
    void thread_select_ln332_fu_294_p3();
    void thread_sext_ln60_fu_390_p1();
    void thread_sub_ln60_1_fu_364_p2();
    void thread_sub_ln60_fu_344_p2();
    void thread_sum_mult_address0();
    void thread_sum_mult_ce0();
    void thread_sum_mult_ce1();
    void thread_sum_mult_we0();
    void thread_sum_mult_we1();
    void thread_tmp_1_fu_353_p3();
    void thread_tmp_6_fu_333_p3();
    void thread_xor_ln330_fu_264_p2();
    void thread_zext_ln332_fu_350_p1();
    void thread_zext_ln335_fu_401_p1();
    void thread_zext_ln60_1_fu_340_p1();
    void thread_zext_ln60_2_fu_360_p1();
    void thread_zext_ln60_3_fu_376_p1();
    void thread_zext_ln60_4_fu_381_p1();
    void thread_zext_ln60_fu_330_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
