set_property MARK_DEBUG true [get_nets design_1_i/top_nqueens_0/U0/fsm_1/ack_in_1]
set_property MARK_DEBUG true [get_nets {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state[4]_i_1__7_n_0}]
set_property MARK_DEBUG true [get_nets {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state_reg[4]_0}]
set_property MARK_DEBUG true [get_nets {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/top_nqueens_0/U0/fsm_1/next_out_1]
set_property MARK_DEBUG true [get_nets design_1_i/top_nqueens_0/U0/fsm_1/next_out_2]
set_property MARK_DEBUG true [get_nets design_1_i/top_nqueens_0/U0/fsm_1/ce__0]
set_property MARK_DEBUG true [get_nets {design_1_i/top_nqueens_0/U0/fsm_1/asout_array[1]_8}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/top_nqueens_0/U0/fsm_1/ack_in_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/top_nqueens_0/U0/fsm_1/asout_array[1]_8}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/top_nqueens_0/U0/fsm_1/ce__0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state[4]_i_1__7_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state_reg[4]_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/top_nqueens_0/U0/fsm_1/FSM_onehot_state_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/top_nqueens_0/U0/fsm_1/next_out_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/top_nqueens_0/U0/fsm_1/next_out_2]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
