set_property SRC_FILE_INFO {cfile:C:/Users/caos1/Desktop/AgustinSilva/Tesis/Vivado/VQFTAXIBUS/VQFTAXIBUS.srcs/constrs_1/new/cons.xdc rfile:../../../VQFTAXIBUS.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports UART1_RX]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports UART1_TX]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports UART1_RX]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports UART1_TX]
