# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mlabadm/Desktop/Github/FPGA/nqueens/nqueens/nqueens/nqueens.srcs/sources_1/bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'nqueens_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mlabadm/Desktop/Github/FPGA/nqueens/nqueens/nqueens/nqueens.srcs/sources_1/bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nqueens_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mlabadm/Desktop/Github/FPGA/nqueens/nqueens/nqueens/nqueens.srcs/sources_1/bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'nqueens_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mlabadm/Desktop/Github/FPGA/nqueens/nqueens/nqueens/nqueens.srcs/sources_1/bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'nqueens_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mlabadm/Desktop/Github/FPGA/nqueens/nqueens/nqueens/nqueens.srcs/sources_1/bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nqueens_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mlabadm/Desktop/Github/FPGA/nqueens/nqueens/nqueens/nqueens.srcs/sources_1/bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'nqueens_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
