# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hnn_fpga/hnn_fpga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hnn_fpga || ORIG_REF_NAME==hnn_fpga} -quiet] -quiet

# IP: bd/hnn_fpga/ip/hnn_fpga_hnn_fpga_0_0/hnn_fpga_hnn_fpga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hnn_fpga_hnn_fpga_0_0 || ORIG_REF_NAME==hnn_fpga_hnn_fpga_0_0} -quiet] -quiet

# IP: bd/hnn_fpga/ip/hnn_fpga_processing_system7_0_0/hnn_fpga_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hnn_fpga_processing_system7_0_0 || ORIG_REF_NAME==hnn_fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/hnn_fpga/ip/hnn_fpga_auto_pc_0/hnn_fpga_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hnn_fpga_auto_pc_0 || ORIG_REF_NAME==hnn_fpga_auto_pc_0} -quiet] -quiet

# IP: bd/hnn_fpga/ip/hnn_fpga_ps7_0_axi_periph_0/hnn_fpga_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hnn_fpga_ps7_0_axi_periph_0 || ORIG_REF_NAME==hnn_fpga_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hnn_fpga/ip/hnn_fpga_rst_ps7_0_100M_0/hnn_fpga_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hnn_fpga_rst_ps7_0_100M_0 || ORIG_REF_NAME==hnn_fpga_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/hnn_fpga/hnn_fpga_ooc.xdc
