# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nqueens/nqueens.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens || ORIG_REF_NAME==nqueens} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_zynq_ultra_ps_e_0_0/nqueens_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==nqueens_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_nqueens_0_0/nqueens_nqueens_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_nqueens_0_0 || ORIG_REF_NAME==nqueens_nqueens_0_0} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_xbar_0/nqueens_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_xbar_0 || ORIG_REF_NAME==nqueens_xbar_0} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_auto_ds_0/nqueens_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_auto_ds_0 || ORIG_REF_NAME==nqueens_auto_ds_0} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_auto_pc_0/nqueens_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_auto_pc_0 || ORIG_REF_NAME==nqueens_auto_pc_0} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_auto_ds_1/nqueens_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_auto_ds_1 || ORIG_REF_NAME==nqueens_auto_ds_1} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_auto_pc_1/nqueens_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_auto_pc_1 || ORIG_REF_NAME==nqueens_auto_pc_1} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_ps8_0_axi_periph_0/nqueens_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_ps8_0_axi_periph_0 || ORIG_REF_NAME==nqueens_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/nqueens/ip/nqueens_rst_ps8_0_99M_0/nqueens_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nqueens_rst_ps8_0_99M_0 || ORIG_REF_NAME==nqueens_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: bd/nqueens/nqueens_ooc.xdc
